# Generated by Django 5.0.1 on 2024-01-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoupang', '0004_alter_review_user_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='mycoupang_review',
        ),
    ]
