# Generated by Django 4.2.5 on 2024-01-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoupang', '0005_alter_review_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='cust_reviews',
        ),
    ]
