# Generated by Django 4.2.5 on 2024-01-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycoupang', '0006_alter_review_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
