# Generated by Django 4.1 on 2024-01-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mycoupang", "0007_delete_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoginRecommend",
            fields=[
                (
                    "review_id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("userid", models.TextField(blank=True, null=True)),
                ("ratings", models.TextField(blank=True, null=True)),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                ("product_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "login_recommend",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NoLoginRecommend",
            fields=[
                (
                    "product_id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("product_rating", models.TextField(blank=True, null=True)),
                ("review_count", models.TextField(blank=True, null=True)),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                ("product_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "no_login_recommend",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductsReviewInfo",
            fields=[
                (
                    "product_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("product_rating", models.TextField(blank=True, null=True)),
                ("review_count", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "products_review_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductsReviewVisualization",
            fields=[
                (
                    "product_id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("product_rating", models.TextField(blank=True, null=True)),
                ("review_count", models.TextField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "products_review_visualization",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductsTable",
            fields=[
                (
                    "product_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("product_name", models.TextField(blank=True, null=True)),
                ("product_url", models.TextField(blank=True, null=True)),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
                ("category_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "products_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewsTable",
            fields=[
                (
                    "review_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("reviewer_name", models.TextField(blank=True, null=True)),
                ("userid", models.TextField(blank=True, null=True)),
                ("review_contents", models.TextField(blank=True, null=True)),
                ("ratings", models.TextField(blank=True, null=True)),
                ("product_name", models.TextField(blank=True, null=True)),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
                ("product_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "reviews_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scenario1",
            fields=[
                (
                    "review_id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("ratings", models.TextField(blank=True, null=True)),
                ("review_contents", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "scenario1",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Wordcloud",
            fields=[
                (
                    "review_id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("category1", models.TextField(blank=True, null=True)),
                ("category2", models.TextField(blank=True, null=True)),
                ("ratings", models.TextField(blank=True, null=True)),
                ("review_contents", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "wordcloud",
                "managed": False,
            },
        ),
    ]
