# Generated by Django 4.1 on 2024-01-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mycoupang", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReviewsTable",
        ),
    ]
