# Generated by Django 4.1 on 2024-02-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mycoupang", "0009_delete_reviewstable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="LoginRecommend",
        ),
        migrations.DeleteModel(
            name="NoLoginRecommend",
        ),
        migrations.DeleteModel(
            name="ProductsReviewInfo",
        ),
        migrations.DeleteModel(
            name="ProductsReviewVisualization",
        ),
        migrations.DeleteModel(
            name="ProductsTable",
        ),
        migrations.DeleteModel(
            name="Scenario1",
        ),
        migrations.DeleteModel(
            name="Wordcloud",
        ),
    ]
